name: adv_image_picker
description: An advanced image picker with our custom UI, depend on AdvCamera (Custom camera with focus and zoom functionality) and ImageList (A native image list view to render image optimally).
version: 2.0.0+3
homepage: https://github.com/ricnaaru/adv_image_picker

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  adv_camera: ^2.0.0+1-nullsafety
  path_provider: ^2.0.1
  image_list: 2.0.1+1

flutter:
  plugin:
    platforms:
      android:
        package: ric.com.advimagepicker
        pluginClass: AdvImagePickerPlugin
      ios:
        pluginClass: AdvImagePickerPlugin