name: adv_image_picker
description: An advanced image picker with our custom UI
version: 1.2.0
homepage: https://github.com/ricnaaru/adv_image_picker

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  adv_camera: ^1.2.0
  path_provider: ^1.6.9
  image_list: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ric.com.advimagepicker
        pluginClass: AdvImagePickerPlugin
      ios:
        pluginClass: AdvImagePickerPlugin